parameters: 
      nlp_symfony.api_key: ''
      nlp_symfony.advanced:
            api_cache: ''
            url: ''
            timeout: ''

services:
      nlp_symfony.response_events:
            class: NlpSymfony\Bundle\Event\RewriteHtml
            arguments:
                  $settings: "@parameter_bag"
            tags:
                  - { name: kernel.event_subscriber }

      nlp_symfony.request_events:
            class: NlpSymfony\Bundle\Event\Request
            arguments:
                  $settings: "@parameter_bag"
            tags:
                  - { name: kernel.event_subscriber }

      nlp_symfony.base_controller:
            class: NlpSymfony\Bundle\Controller\BaseController
            
                  
