parameters: 
      nlp_symfony.api_key: ''
      nlp_symfony.advanced:
            api_cache: '%kernel.cache_dir%'
            url: 'https://www.nopow-link.com'
            timeout: '2.0'

services:
      nlp_symfony.response_events:
            class: NlpSymfony\Bundle\Event\RewriteHtml
            arguments:
                  $settings: "@parameter_bag"
            tags:
                  - { name: kernel.event_subscriber }

      nlp_symfony.request_events:
            class: NlpSymfony\Bundle\Event\Request
            arguments:
                  $settings: "@parameter_bag"
            tags:
                  - { name: kernel.event_subscriber }

      NlpSymfony\Bundle\Controller\TestController:
            class: NlpSymfony\Bundle\Controller\TestController
            arguments: 
            tags: ['controller.service_arguments']
            calls:
                  - ['setContainer', ['@service_container']]

      NlpSymfony\Bundle\Controller\CertifyController:
            class: NlpSymfony\Bundle\Controller\CertifyController
            arguments: 
            tags: ['controller.service_arguments']
            calls:
                  - ['setContainer', ['@service_container']]
            
      
            
                  
